name: Feature request
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What would you like?
      description: Describe the feature and the problem it solves for you.
      placeholder: It would be great if...
    validations:
      required: true
